# Generated by Django 3.1.2 on 2020-10-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_auto_20201010_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
